### ISSUE TITLE
Display number of times shortened URL has been used.

### ISSUE THREAD

**Issue by Raj-m01** [Raj-m01/Short-it#5]
Add count of number of times website has been visited using its shortened URL .
#### Reference/hint : 
* Edit the model to store URL visit count.
* Increment and save the count when URL is redirected using shortened URL . (in views.py 'direct_url' function)

**Comment by moazfarrukh** [comment]
i'd like to work on this

**Comment by Raj-m01** [comment]
> i'd like to work on this
> 

Ok. I m assigning you.

**Comment by moazfarrukh** [comment]
#6

**Comment by moazfarrukh** [comment]
done!
